# Generated by Django 2.1.3 on 2018-11-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20181113_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='target',
            field=models.CharField(choices=[('COMMON', 'Para todos'), ('STUDENTS', 'Alumnos'), ('TEACHER', 'Profesores')], default='COMMON', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
